name: Update Podcast Feed

on:
  schedule:
    # 22:11 UTC on Saturday is 06:11 AM HKT on Sunday
    - cron: '11 22 * * 6'
  workflow_dispatch: # Allows you to run this manually anytime from the GitHub UI

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Podcast RSS Feed
        run: python generate_feed.py

      - name: Upload Artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
